//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCost_ConsumptionCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refuelling
    {
        public int RefuelingId { get; set; }
        public double Amount { get; set; }
        public double Cost { get; set; }
        public double Mileage { get; set; }
        public System.DateTime DateRefuel { get; set; }
        public int fk_UserId { get; set; }
        public int fk_CarId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
