//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCost_ConsumptionCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int TravelId { get; set; }
        public string TravelStart { get; set; }
        public string TravelTarget { get; set; }
        public string TravelPurpose { get; set; }
        public int fk_UserId { get; set; }
        public int fk_CarId { get; set; }
        public double TravelStartMileage { get; set; }
        public double TravelTargetMileage { get; set; }
        public System.DateTime DateTravel { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
